server:
  port: 9094
spring:
  application:
    name: kab-survey-consumer
  mvc:
    view:
      prefix: /templates/
      suffix: .html
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
feign:
  hystrix:
    enabled: true