server:
  port: 9092
spring:
  application:
    name: kab-consultation-consumer
  mvc:
    view:
      prefix: /templates/
      suffix: .html
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
feign:
  hystrix:
    enabled: true