server:
  port: 9090
spring:
  application:
    name: kab-member-consumer
  mvc:
    view:
      prefix: /templates/
      suffix: .html
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
feign:
  hystrix:
    enabled: true
kab-member-provider:
  ribbon:
    NFLoadBalanceRuleClassName: com.netflix.loadbalance.RandonRule #采用交替执行策略