server:
  port: 5000
spring:
  application:
    name: kab-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Beeru4/kab_.git
          username: Beeru4
          password: wotoubeerus6
          search-paths: properties
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/